{% set name = "cake" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cake-build/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 467158d7f6455f4dfc97a9ccfd7688c84531427c7089ad83f69b09190892d4a7

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} --help

about:
  home: https://cakebuild.net
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cake (C# Make) is a cross platform build automation system
  dev_url: https://github.com/cake-build/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
