{% set name = "cake" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cake-build/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2f666eb901a9e0ec0155fe724876008cae94c542939c5ae989bbd8dcad93949b

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} --help

about:
  home: https://cakebuild.net
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cake (C# Make) is a cross platform build automation system
  dev_url: https://github.com/cake-build/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
