context:
  version: "6.2.0"

package:
  name: cake
  version: ${{ version }}

source:
  url: https://github.com/cake-build/cake/archive/v${{ version }}.tar.gz
  sha256: 5fe61d9df142ef8c1d15def04dc3a634f07459f0ecc6098efb760207ddc6a452

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - cake --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cake (C# Make) is a cross platform build automation system
  homepage: https://cakebuild.net
  repository: https://github.com/cake-build/cake

extra:
  recipe-maintainers:
    - danielnachun
