context:
  version: "5.0.0"

package:
  name: cake
  version: ${{ version }}

source:
  url: https://github.com/cake-build/cake/archive/v${{ version }}.tar.gz
  sha256: 0c77a4a8626b1f6aa886e542026f33e2645bda7177e66c6ca1f60a6cf80b9bf0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - cake --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cake (C# Make) is a cross platform build automation system
  homepage: https://cakebuild.net
  repository: https://github.com/cake-build/cake

extra:
  recipe-maintainers:
    - danielnachun
