context:
  version: "6.1.0"

package:
  name: cake
  version: ${{ version }}

source:
  url: https://github.com/cake-build/cake/archive/v${{ version }}.tar.gz
  sha256: 90c172d5ca8bd3b274cb7cbadca0a4de7f627663f2915c3ac33fe99ae7937f0d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - cake --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cake (C# Make) is a cross platform build automation system
  homepage: https://cakebuild.net
  repository: https://github.com/cake-build/cake

extra:
  recipe-maintainers:
    - danielnachun
