context:
  version: "6.3.0"

package:
  name: cake
  version: ${{ version }}

source:
  url: https://github.com/cake-build/cake/archive/v${{ version }}.tar.gz
  sha256: 6db077c1a78323dce1b53a799e5c53ed4d864dd4f6c6d206d46e5d71733e3dcf

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - cake --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Cake (C# Make) is a cross platform build automation system
  homepage: https://cakebuild.net
  repository: https://github.com/cake-build/cake

extra:
  recipe-maintainers:
    - danielnachun
